-- AlterTable
ALTER TABLE "Match" ALTER COLUMN "homeTeamId" DROP NOT NULL,
ALTER COLUMN "homeTeamName" DROP NOT NULL,
ALTER COLUMN "awayTeamId" DROP NOT NULL,
ALTER COLUMN "awayTeamName" DROP NOT NULL;
